### ISSUE TITLE
`anonymize` attribute should be written without "true" value inside the tag

### ISSUE THREAD

**Issue by andrewspy** [wasc-io/iron-ga#2]
Boolean attribute with `true` value should be written as below:-

```html
<iron-ga code="UA-XXXXXX-Y" anonymize></iron-ga>
```

Here's the reference:-

[Configuring boolean properties](https://www.polymer-project.org/2.0/docs/devguide/properties#attribute-deserialization)

_For a Boolean property to be configurable from markup, it must default to false. If it defaults to true, you cannot set it to false from markup, since the presence of the attribute, with or without a value, equates to true. This is the standard behavior for attributes in the web platform._

**Comment by NicolaiSchmid** [comment]
Your're right, I will fix the README later this evening
