### ISSUE TITLE
Propose boolean attribute `log` for logging `track-page` and `track-event` event

### ISSUE THREAD

**Issue by andrewspy** [wasc-io/iron-ga#3]
Propose markup as below to enable logging, which is implemented by [polymerfire](https://www.webcomponents.org/element/firebase/polymerfire/elements/firebase-document#property-log).

```html
<iron-ga
    log
    code="UA-XXXXXX-Y"
    anonymize>
</iron-ga>
```

Suggest to log event for both `track-page` and `track-event` with event detail to ease development, especially for people that are new to Google Analytics.

**Comment by NicolaiSchmid** [comment]
I can implement your proposal, but wouldn't it be more handy, if you could just enable logging globally instead of having to change your markup. 
In step 3 of the twelve factor guide it is suggested to store your configuration in the environment and not the Code itself. Which your solution is in vilation of.

**Comment by andrewspy** [comment]
I'm no expert in software development, but here's my opinion:-

1. Web component are meant to be modular and self-contained, so it's not a good idea to touch global variable. If you are talking about application, then it's a different story.
2. Web component are more for front-end development (as oppose to server/back-end). Storing configuration in environment is more for back-end development (such as Firebase Cloud Functions)
3. As a front-end development environment, developer usually would just see the log from Chrome DevTools, which unlike back-end service, that needs to log into a physical log file.
4. By using `log` attribute, the developer have the option to set `log` option both pragramatically (via javascript), as well as using markup/tags which most front-end developer do.

**Comment by NicolaiSchmid** [comment]
You're right, you've convinced me.
